#!/bin/sh
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export PATH="/usr/local/bin:$HOME/bin:$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export TERMINAL="kitty"

if [[ $(uname -s) == "Darwin" ]]; then
    export PATH=$PATH:/opt/homebrew/bin
    export PATH=$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
    export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/opt/openssl/lib
fi

export PTPYTHON_CONFIG_HOME=$HOME/.config/ptpython/
